import os

DEBUG = True 

TWITTER_CONSUMER_KEY = os.environ["TWITTER_CONSUMER_KEY"]
TWITTER_CONSUMER_SECRET = os.environ["TWITTER_CONSUMER_SECRET"]
TWITTER_ACCESS_TOKEN = os.environ["TWITTER_ACCESS_TOKEN"]
TWITTER_ACCESS_TOKEN_SECRET = os.environ["TWITTER_ACCESS_TOKEN_SECRET"]
TONE_ANALYSER_USERNAME = os.environ["TONE_ANALYSER_USERNAME"]
TONE_ANALYSER_PASSWORD = os.environ["TONE_ANALYSER_PASSWORD"]